services:
  client-app:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  server-api:
    build:
      context: ./server-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server-api:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
